apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
data:
  Key3: dmFsdWUx

---
apiVersion: v1
kind: Pod
metadata:
  name: ngnix-secret
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:stable
      env:
        - name: BEST_VARIABLE
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: Key3
