apiVersion: v1
kind: Namespace
metadata:
  name: neptune

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neptune-10ab
  namespace: neptune
spec:
  replicas: 3
  selector:
    matchLabels:
      app: neptune-10ab
  template:
    metadata:
      labels:
        app: neptune-10ab
    spec:
      containers:
        - name: neptune-pod-10ab
          image: httpd:2.4-alpine
          resources:
            requests:
              memory: "20Mi"
