apiVersion: v1
kind: Namespace
metadata:
  name: btu-final

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: btu-final
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          env:
            - name: NGINX__PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  namespace: btu-final
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-deployment
  namespace: btu-final
spec:
  rules:
  - host: nginx.final.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-deployment
            port:
              number: 80
