apiVersion: v1
kind: Pod
metadata:
  name: nginx-resources
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:stable
      resources:
        requests:
          cpu: "300m"
          memory: "1Gi"
