apiVersion: v1
kind: Pod
metadata:
  name: nginx-resources
  namespace: btu-final
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "200m"
        memory: "1Gi"
