apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: exam
  hostPath:
    path: "/opt/KDSP00101/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: exam

---
apiVersion: v1
kind: Pod
metadata:
  name: my-storage-pod
  labels:
    app: my-storage-app
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-storage
  volumes:
    - name: task-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
